# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\cyril\Downloads\page_reglagesv2.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Reglages(object):
    def setupUi(self, Reglages):
        Reglages.setObjectName(_fromUtf8("Reglages"))
        #Reglages.resize(518, 312)
        #Reglages.setMaximumSize(QtCore.QSize(518, 512))
        Reglages.showMaximized()  #plein écran
        #Reglages.showFullScreen()  #affichage plein ecran sans pouvoir reduire fermer etc
        self.gridLayout = QtGui.QGridLayout(Reglages)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.PushButton_retour = QtGui.QPushButton(Reglages)
        self.PushButton_retour.setObjectName(_fromUtf8("PushButton_retour"))
        self.verticalLayout_5.addWidget(self.PushButton_retour)
        self.PushButton_valider = QtGui.QPushButton(Reglages)
        self.PushButton_valider.setObjectName(_fromUtf8("PushButton_valider"))
        self.verticalLayout_5.addWidget(self.PushButton_valider)
        self.gridLayout.addLayout(self.verticalLayout_5, 3, 6, 1, 1)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_vide_1 = QtGui.QLabel(Reglages)
        self.label_vide_1.setText(_fromUtf8(""))
        self.label_vide_1.setObjectName(_fromUtf8("label_vide_1"))
        self.verticalLayout_3.addWidget(self.label_vide_1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.label_freq_2 = QtGui.QLabel(Reglages)
        self.label_freq_2.setObjectName(_fromUtf8("label_freq_2"))
        self.verticalLayout_3.addWidget(self.label_freq_2)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.label_nbech2 = QtGui.QLabel(Reglages)
        self.label_nbech2.setObjectName(_fromUtf8("label_nbech2"))
        self.verticalLayout_3.addWidget(self.label_nbech2)
        self.gridLayout.addLayout(self.verticalLayout_3, 1, 5, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.comboBox_accel = QtGui.QComboBox(Reglages)
        self.comboBox_accel.setObjectName(_fromUtf8("comboBox_accel"))
        self.comboBox_accel.addItem(_fromUtf8(""))
        self.comboBox_accel.addItem(_fromUtf8(""))
        self.comboBox_accel.addItem(_fromUtf8(""))
        self.verticalLayout_2.addWidget(self.comboBox_accel)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.comboBox_freq = QtGui.QComboBox(Reglages)
        self.comboBox_freq.setObjectName(_fromUtf8("comboBox_freq"))
        self.comboBox_freq.addItem(_fromUtf8(""))
        self.comboBox_freq.addItem(_fromUtf8(""))
        self.comboBox_freq.addItem(_fromUtf8(""))
        self.verticalLayout_2.addWidget(self.comboBox_freq)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.comboBox_nbech = QtGui.QComboBox(Reglages)
        self.comboBox_nbech.setObjectName(_fromUtf8("comboBox_nbech"))
        self.comboBox_nbech.addItem(_fromUtf8(""))
        self.comboBox_nbech.addItem(_fromUtf8(""))
        self.comboBox_nbech.addItem(_fromUtf8(""))
        self.comboBox_nbech.addItem(_fromUtf8(""))
        self.verticalLayout_2.addWidget(self.comboBox_nbech)
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 3, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_accel = QtGui.QLabel(Reglages)
        self.label_accel.setObjectName(_fromUtf8("label_accel"))
        self.verticalLayout.addWidget(self.label_accel)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.label_freq = QtGui.QLabel(Reglages)
        self.label_freq.setObjectName(_fromUtf8("label_freq"))
        self.verticalLayout.addWidget(self.label_freq)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.label_nbech = QtGui.QLabel(Reglages)
        self.label_nbech.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_nbech.setObjectName(_fromUtf8("label_nbech"))
        self.verticalLayout.addWidget(self.label_nbech)
        self.gridLayout.addLayout(self.verticalLayout, 1, 2, 1, 1)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_2 = QtGui.QLabel(Reglages)
        self.label_2.setText(_fromUtf8(""))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_4.addWidget(self.label_2)
        spacerItem6 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem6)
        self.label_valfmax = QtGui.QLabel(Reglages)
        self.label_valfmax.setObjectName(_fromUtf8("label_valfmax"))
        self.verticalLayout_4.addWidget(self.label_valfmax)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem7)
        self.label_valresolution = QtGui.QLabel(Reglages)
        self.label_valresolution.setObjectName(_fromUtf8("label_valresolution"))
        self.verticalLayout_4.addWidget(self.label_valresolution)
        self.gridLayout.addLayout(self.verticalLayout_4, 1, 6, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem8, 0, 3, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem9, 2, 6, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem10, 1, 4, 1, 1)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem11, 1, 1, 1, 1)
        spacerItem12 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem12, 4, 6, 1, 1)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem13, 2, 7, 1, 1)
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem14, 1, 0, 1, 1)
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem15, 2, 8, 1, 1)

        self.retranslateUi(Reglages)
        QtCore.QMetaObject.connectSlotsByName(Reglages)

    def retranslateUi(self, Reglages):
        Reglages.setWindowTitle(_translate("Reglages", "REGLAGES", None))
        self.PushButton_retour.setText(_translate("Reglages", "Retour", None))
        self.PushButton_valider.setText(_translate("Reglages", "Valider", None))
        self.label_freq_2.setText(_translate("Reglages", "Fréquence maximale mesurable :", None))
        self.label_nbech2.setText(_translate("Reglages", "      Résolution en fréquence :", None))
        self.comboBox_accel.setItemText(0, _translate("Reglages", "      ± 2g", None))
        self.comboBox_accel.setItemText(1, _translate("Reglages", "      ± 4g", None))
        self.comboBox_accel.setItemText(2, _translate("Reglages", "      ± 8g", None))
        self.comboBox_freq.setItemText(0, _translate("Reglages", "      100 Hz", None))
        self.comboBox_freq.setItemText(1, _translate("Reglages", "      200 Hz", None))
        self.comboBox_freq.setItemText(2, _translate("Reglages", "      400 Hz", None))
        self.comboBox_nbech.setItemText(0, _translate("Reglages", "        128", None))
        self.comboBox_nbech.setItemText(1, _translate("Reglages", "        256", None))
        self.comboBox_nbech.setItemText(2, _translate("Reglages", "        512", None))
        self.comboBox_nbech.setItemText(3, _translate("Reglages", "       1024", None))
        self.label_accel.setText(_translate("Reglages", "       Gamme d\'accélération :    ", None))
        self.label_freq.setText(_translate("Reglages", "Fréquence d\'échantillionnage :", None))
        self.label_nbech.setText(_translate("Reglages", "     Nombre d\'échantillons :      ", None))
        self.label_valfmax.setText(_translate("Reglages", "100 Hz", None))
        self.label_valresolution.setText(_translate("Reglages", "1 Hz", None))

